// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RouteController ...
type RouteController struct {
	ID                     int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AutonomousSystemNumber int32    `protobuf:"varint,2,opt,name=autonomous_system_number,json=autonomousSystemNumber,proto3" json:"autonomous_system_number,omitempty"`
	IP                     string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

// Reset ...
func (m *RouteController) Reset() { *m = RouteController{} }

// String ...
func (m *RouteController) String() string { return proto.CompactTextString(m) }

// ProtoMessage ...
func (*RouteController) ProtoMessage() {}

// Descriptor ...
func (*RouteController) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

// XXX_Unmarshal ...
func (m *RouteController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteController.Unmarshal(m, b)
}

// XXX_Marshal ...
func (m *RouteController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteController.Marshal(b, m, deterministic)
}

// XXX_Merge ...
func (m *RouteController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteController.Merge(m, src)
}

// XXX_Size ...
func (m *RouteController) XXX_Size() int {
	return xxx_messageInfo_RouteController.Size(m)
}

// XXX_DiscardUnknown ...
func (m *RouteController) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteController.DiscardUnknown(m)
}

var xxx_messageInfo_RouteController proto.InternalMessageInfo

// GetID ...
func (m *RouteController) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

// GetAutonomousSystemNumber ...
func (m *RouteController) GetAutonomousSystemNumber() int32 {
	if m != nil {
		return m.AutonomousSystemNumber
	}
	return 0
}

// GetIP ...
func (m *RouteController) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

// AutonomousSystem ...
type AutonomousSystem struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	LinkCapacity         int32    `protobuf:"varint,2,opt,name=link_capacity,json=linkCapacity,proto3" json:"link_capacity,omitempty"`
	Cost                 int32    `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

// Reset ...
func (m *AutonomousSystem) Reset() { *m = AutonomousSystem{} }

// String ...
func (m *AutonomousSystem) String() string { return proto.CompactTextString(m) }

// ProtoMessage ...
func (*AutonomousSystem) ProtoMessage() {}

// Descriptor ...
func (*AutonomousSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

// XXX_Unmarshal ...
func (m *AutonomousSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutonomousSystem.Unmarshal(m, b)
}

// XXX_Marshal ...
func (m *AutonomousSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutonomousSystem.Marshal(b, m, deterministic)
}

// XXX_Merge ...
func (m *AutonomousSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutonomousSystem.Merge(m, src)
}

// XXX_Size ...
func (m *AutonomousSystem) XXX_Size() int {
	return xxx_messageInfo_AutonomousSystem.Size(m)
}

// XXX_DiscardUnknown ...
func (m *AutonomousSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_AutonomousSystem.DiscardUnknown(m)
}

var xxx_messageInfo_AutonomousSystem proto.InternalMessageInfo

// GetNumber ...
func (m *AutonomousSystem) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

// GetLinkCapacity ...
func (m *AutonomousSystem) GetLinkCapacity() int32 {
	if m != nil {
		return m.LinkCapacity
	}
	return 0
}

// GetCost ...
func (m *AutonomousSystem) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

// UpdateMessage ...
type UpdateMessage struct {
	UUID                        string              `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SourceRouteController       *RouteController    `protobuf:"bytes,2,opt,name=source_route_controller,json=sourceRouteController,proto3" json:"source_route_controller,omitempty"`
	DestinationAutonomousSystem []*AutonomousSystem `protobuf:"bytes,3,rep,name=destination_autonomous_system,json=destinationAutonomousSystem,proto3" json:"destination_autonomous_system,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}            `json:"-"`
	XXX_unrecognized            []byte              `json:"-"`
	XXX_sizecache               int32               `json:"-"`
}

// Reset ...
func (m *UpdateMessage) Reset() { *m = UpdateMessage{} }

// String ...
func (m *UpdateMessage) String() string { return proto.CompactTextString(m) }

// ProtoMessage ...
func (*UpdateMessage) ProtoMessage() {}

// Descriptor ...
func (*UpdateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

// XXX_Unmarshal ...
func (m *UpdateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMessage.Unmarshal(m, b)
}

// XXX_Marshal ...
func (m *UpdateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMessage.Marshal(b, m, deterministic)
}

// XXX_Merge ...
func (m *UpdateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMessage.Merge(m, src)
}

// XXX_Size ...
func (m *UpdateMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateMessage.Size(m)
}

// XXX_DiscardUnknown ...
func (m *UpdateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMessage proto.InternalMessageInfo

// GetUUID ...
func (m *UpdateMessage) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

// GetSourceRouteController ...
func (m *UpdateMessage) GetSourceRouteController() *RouteController {
	if m != nil {
		return m.SourceRouteController
	}
	return nil
}

// GetDestinationAutonomousSystem ...
func (m *UpdateMessage) GetDestinationAutonomousSystem() []*AutonomousSystem {
	if m != nil {
		return m.DestinationAutonomousSystem
	}
	return nil
}

func init() {
	proto.RegisterType((*RouteController)(nil), "model.RouteController")
	proto.RegisterType((*AutonomousSystem)(nil), "model.AutonomousSystem")
	proto.RegisterType((*UpdateMessage)(nil), "model.UpdateMessage")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4b, 0x4f, 0xc2, 0x40,
	0x14, 0x85, 0xd3, 0xf2, 0x88, 0x0c, 0x12, 0xcd, 0x24, 0x96, 0xc6, 0x47, 0x20, 0xb8, 0x61, 0x23,
	0x24, 0xb8, 0x71, 0x2b, 0xb0, 0x61, 0x21, 0x31, 0x63, 0x58, 0xb9, 0x68, 0xda, 0xe9, 0x58, 0x27,
	0xb6, 0xbd, 0xcd, 0x3c, 0x16, 0xc4, 0x7f, 0xea, 0x82, 0x05, 0xbf, 0xc4, 0x70, 0x99, 0xa8, 0xa9,
	0xbb, 0x7b, 0xee, 0xe9, 0x39, 0xb7, 0xfd, 0x4a, 0xba, 0x05, 0xa4, 0x22, 0x9f, 0x54, 0x0a, 0x0c,
	0xd0, 0x16, 0x8a, 0xcb, 0xbb, 0x4c, 0x9a, 0x77, 0x9b, 0x4c, 0x38, 0x14, 0xd3, 0x0c, 0x32, 0x98,
	0xa2, 0x9b, 0xd8, 0x37, 0x54, 0x28, 0x70, 0x3a, 0xa6, 0x46, 0x9f, 0xe4, 0x8c, 0x81, 0x35, 0x62,
	0x01, 0xa5, 0x51, 0x90, 0xe7, 0x42, 0xd1, 0x80, 0xf8, 0x32, 0x0d, 0xbd, 0xa1, 0x37, 0x6e, 0xcd,
	0xdb, 0xfb, 0xdd, 0xc0, 0x5f, 0x2d, 0x99, 0x2f, 0x53, 0xfa, 0x40, 0xc2, 0xd8, 0x1a, 0x28, 0xa1,
	0x00, 0xab, 0x23, 0xbd, 0xd5, 0x46, 0x14, 0x51, 0x69, 0x8b, 0x44, 0xa8, 0xd0, 0x3f, 0x3c, 0xcd,
	0x82, 0x5f, 0xff, 0x05, 0xed, 0x35, 0xba, 0xd8, 0x58, 0x85, 0x8d, 0xa1, 0x37, 0xee, 0xb8, 0xc6,
	0x67, 0xe6, 0xcb, 0x6a, 0xc4, 0xc9, 0xf9, 0x63, 0x2d, 0x41, 0x03, 0xd2, 0x76, 0x9d, 0xf8, 0x06,
	0xcc, 0x29, 0x7a, 0x4b, 0x7a, 0xb9, 0x2c, 0x3f, 0x22, 0x1e, 0x57, 0x31, 0x97, 0x66, 0xeb, 0x4e,
	0x9e, 0x1e, 0x96, 0x0b, 0xb7, 0xa3, 0x94, 0x34, 0x39, 0x68, 0x83, 0xa7, 0x5a, 0x0c, 0xe7, 0xd1,
	0x97, 0x47, 0x7a, 0x9b, 0x2a, 0x8d, 0x8d, 0x78, 0x12, 0x5a, 0xc7, 0x99, 0xa0, 0xd7, 0xa4, 0x69,
	0xad, 0xfb, 0xc4, 0xce, 0xfc, 0x64, 0xbf, 0x1b, 0x34, 0x37, 0x9b, 0xd5, 0x92, 0xe1, 0x96, 0xae,
	0x49, 0x5f, 0x83, 0x55, 0x5c, 0x44, 0xea, 0x00, 0x26, 0xe2, 0x3f, 0x64, 0xf0, 0x64, 0x77, 0x16,
	0x4c, 0x8e, 0xd8, 0x6b, 0xdc, 0xd8, 0xc5, 0x31, 0x56, 0xc7, 0xf9, 0x4a, 0x6e, 0x52, 0xa1, 0x8d,
	0x2c, 0x63, 0x23, 0xa1, 0x8c, 0xfe, 0x21, 0x0c, 0x1b, 0xc3, 0xc6, 0xb8, 0x3b, 0xeb, 0xbb, 0xd6,
	0x3a, 0x10, 0x76, 0xf5, 0x27, 0x5d, 0x37, 0x93, 0x36, 0xfe, 0xc5, 0xfb, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x0e, 0x61, 0x83, 0xd2, 0x0a, 0x02, 0x00, 0x00,
}
