#!/usr/bin/env bash

function add_tracer() {
    local -r root="$1"; \
    find "$root" -type f \
                    -a -name *.go \
                    -a -not -name *_test.go \
                    -a -not -name *.pb.go | while read file; do \
        IFS=$'\n'; \
        sed -i 's/.*\[CALL-STACK\].*//g' "$file" ; \
        targets=($(grep -noP '(?<=func ).*?(?= \{)' "$file")); \
        for line in "${targets[@]}";do \
            number=$(echo "$line"|cut -d: -f1) ; \
            signature=$(echo "$line"|cut -d: -f2) ; \
            to_add="fmt.Println(\"[CALL-STACK] [$file] : $signature \")"; \
            sed -i.bac "$((number+1)) i $to_add" "$file" ; \
            unset number; unset signature;unset to_add; \
        done;
        goimports -w "$file";unset file; unset IFS; \
    done;
}
if [ -z "${BASH_SOURCE+x}" ]; then
    add_tracer "$@"
    exit $?
else
    if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
        add_tracer "$@"
        exit $?
    else
        export -f add_tracer 
    fi
fi