image:
  file: contrib/gitpod/.gitpod.Dockerfile
tasks:
  - init: >
      GO111MODULE=off go get -u -v github.com/cuonglm/gocmt &&
      GO111MODULE=off go get -u -v github.com/mohae/nocomment/cmd/nocomment &&
      GO111MODULE=off go get -u -v honnef.co/go/tools/cmd/staticcheck &&
      GO111MODULE=off go get -u -d -v github.com/magefile/mage &&
      GO111MODULE=off go get -v github.com/golang/protobuf/protoc-gen-go &&
      GO111MODULE=off go get -v github.com/gogo/protobuf/proto &&
      GO111MODULE=off go get -v github.com/gogo/protobuf/jsonpb &&
      GO111MODULE=off go get -v github.com/gogo/protobuf/protoc-gen-gogo &&
      GO111MODULE=off go get -v github.com/gogo/protobuf/gogoproto &&
      GO111MODULE=off go get -v github.com/gogo/protobuf/protoc-gen-gofast &&
      GO111MODULE=off go get -v github.com/gogo/protobuf/protoc-gen-gogofast &&
      GO111MODULE=off go get -v github.com/gogo/protobuf/protoc-gen-gogofaster &&
      GO111MODULE=off go get -v github.com/gogo/protobuf/protoc-gen-gogoslick &&
      GO111MODULE=off go get -v golang.org/x/tools/cmd/... &&
      GO111MODULE=off go get -u -v github.com/gobuffalo/packr/v2/... &&
      GO111MODULE=off go get -u -v github.com/gobuffalo/packr/v2/packr2 &&
      cd $GOPATH/src/github.com/magefile/mage &&
      GO111MODULE=off go run bootstrap.go &&
      cd $GOPATH/src/honnef.co/go/tools/cmd/staticcheck &&
      git checkout 2019.2 &&
      go get &&
      go install &&
      cd /workspace/go/src/github.com/da-moon/coe865-final
vscode:
  extensions:
    - wmaurer.change-case@1.0.0:EFbL568cjs07Ajw2vuXcpw==
    - emeraldwalk.RunOnSave@0.2.0:6DpPyy2kCQ1Ug+O4phQ/Lw==
    - vscode-snippet.snippet@0.8.0:heDB4eLEEI1w13OjYacLlQ==
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==
    - kevinkyang.auto-comment-blocks@1.0.1:pNOhuU1hQbN6l84Rky73aw==
    - micnil.vscode-checkpoints@1.3.0:dkiLAf0Y/WfLURngDOsDdA==
    - alefragnani.Bookmarks@11.0.0:m2p0avZpvPtfi0p13tawPA==
    - lkytal.pomodoro@1.1.3:002RH2DJY9QFkufZ2J2U7w==
    - piotrpalarz.vscode-gitignore-generator@1.0.1:iNyE+Zbg+DD32/VtNMgUrg==
    - aaron-bond.better-comments@2.0.5:YKNfOclR4e8XAxlj4xp2AA==
    - CodeStream.codestream@6.5.0:s+H7WY/FQ66qVvU5gAEkjQ==
    - softwaredotcom.swdc-vscode@2.1.45:pmY4dKH5T5NIhWJJpHr5Gw==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
